### ISSUE TITLE
Prefix, suffix

### ISSUE THREAD

**Issue by CalebKester** [ngoodrum/FluidResponsiveGrid#7]
Probably should add in prefix, suffix.

**Comment by mikeadesign** [comment]
There should be a push/pull available if that is what you are referring to? May be part of my branch or local code tho

-----Original Message-----

**Comment by CalebKester** [comment]
No, prefix and suffix, see: http://unsemantic.com/demo-responsive and http://unsemantic.com/css-documentation#6-prefix-amp-suffix-classes

I'll try and submit a pull request with it in on Monday.
