### ISSUE TITLE
Non Responsive Grid

### ISSUE THREAD

**Issue by CalebKester** [ngoodrum/FluidResponsiveGrid#8]
One of the lingering issues that we should address before we launch this is using this grid for non-responsive sites.

Should we just tell people to remove the media queries? Or should we just include a separate file that way they don't need to do any prep work and can just plug and chug.

**Comment by CalebKester** [comment]
Created a basic version in my repo: https://github.com/CalebKester/FluidResponsiveGrid

**Comment by mikeadesign** [comment]
I have a gridFixed.css file that removes the media queries and such locally testing.

I can post it up after some additional cleanup

-----Original Message-----
